### PR TITLE
Flurry of Blows compatibility with CombatModes plugin

### PR DESCRIPTION
**Pull request by BhaalM**

### CODE REVIEW

**Comment by Liareth** [comment]
tbh, this seems a bit weird to me. Why have it in the Weapons plugin at all? Shouldn't this exist purely in the CombatModes plugin?

**Comment by BhaalM** [comment]
@Liareth if you look at my last commit I removed the hook from the weapon plugin. Now it is only in the CombatModes plugin.

**Comment by Liareth** [comment]
But it uses the messaging system, and requires NWNX_Weapons to be enabled for it to turn on? What is the purpose of that? Wouldn't it be better to just delete it completely from NWNX_Weapons and add it to NWNX_CombatModes?

**Comment by BhaalM** [comment]
Because the new monk weapons are defined in the Weapon plugin (not only for the flurry of blows but for the monk attack table). If you don't define new monk weapons you don't need to activate the flurry of blows thing.

**Pull request merged**
