### PR TITLE
Added Utils::UpdateClientObject(ForPlayer) and NWNX_Util_UpdateClientObject

### PR DESCRIPTION
**Pull request by Cjreek**

### CODE REVIEW

**Review by mtijanic — APPROVED** [review]
I'll let Daz merge, but looks good.

**Comment by Aschent89** [comment]
Out of curiosity, would this solve for the issue of edited armor pieces not visually showing on a PC until unequip/re-equip? Or am I reading too much into this function?

**Comment by Daztek** [comment]
No, that needs client changes.

**Comment by Daztek** [comment]
Cherry-picked into branch build8193.36

**Pull request closed without merging**
