### PR TITLE
Add NWNX_Player_ReloadTlk()

### PR DESCRIPTION
**Pull request by julien-lecomte**
In case you want the less capable, but also less dangerous thing ;-)

Tested with 2 tlks: faerun_en.tlk and faerun_fr.tlk. Both served with nwsync.

Changed from "en" to "fr" via these two lines:

```
NWNX_Player_SetResManOverride(oSpeaker, RESTYPE_TLK, "faerun_en", "faerun_fr");
NWNX_Player_ReloadTlk(oSpeaker);
```

### CODE REVIEW

**Comment by julien-lecomte** [comment]
Hadn't noticed that this PR embarked other modifications that were not meant to be here.

**Comment by julien-lecomte** [comment]
To continue on the conversation we had on discord: is this "good enough"? Or do you plan on doing a more complicated version with better features?

For my usage, it's all that I need. The only issue I could regret is not being able to set the tlk before chargen (for new feats or classes for example)

**Comment by Daztek** [comment]
You could probably write a tweak that sends the tlk resource override + tlk reload before chargen

**Comment by julien-lecomte** [comment]
I can look into this.

**Comment by mtijanic** [comment]
Eh, let's just merge this anyway. Worst case, it'll get moved to deprecated as a wrapper of something else later. Or, removed and replaced with the tweak. But I think it's fine as is.

Please resolve the changelog conflict and I'll merge.

**Pull request merged**
