### PR TITLE
Plugin: CombatModes

### PR DESCRIPTION
**Pull request by Daztek**
Basically Liareth's stuff from #15 in its own plugin except the following since I'm not sure it would work as intended.

>// ToggleMode gets called with modes which are +1 to what the script constants expect.
  // It then calls SetCombatMode with the 'proper' modes.
  // To simplify things, we just correct the mode we dispatch here, so the game events
  // receive what they expect to.

These are the constants from nwscript:

>// Combat Mode Defines
int COMBAT_MODE_INVALID                 = 0;// 0 
int COMBAT_MODE_PARRY                   = 1;// mode correctly returns 1
int COMBAT_MODE_POWER_ATTACK            = 2;// modet correctly returns 2
int COMBAT_MODE_IMPROVED_POWER_ATTACK   = 3;//  mode correctly returns 3
 // counterspell aka 4 doesn't have a constant for some reason, mode correctly returns 4
int COMBAT_MODE_FLURRY_OF_BLOWS         = 4;// mode returns 5
int COMBAT_MODE_RAPID_SHOT              = 5;// mode returns 6
int COMBAT_MODE_EXPERTISE               = 6;// mode returns 7
int COMBAT_MODE_IMPROVED_EXPERTISE      = 7;// mode returns 8
int COMBAT_MODE_DEFENSIVE_CASTING       = 8;//mode returns 9
int COMBAT_MODE_DIRTY_FIGHTING          = 9; // mode returns 10
int COMBAT_MODE_DEFENSIVE_STANCE        = 10;// mode returns 11

Sherincall gave me the following list which is correct

>NONE                    0
PARRY                   1
POWER_ATTACK            2
IMPROVED_POWER_ATTACK   3
COUNTERSPELL            4
FLURRY_OF_BLOWS         5
RAPID_SHOT              6
EXPERTISE               7
IMPROVED_EXPERTISE      8
DEFENSIVE_CASTING       9
DIRTY_FIGHTING          10
DEFENSIVE_STANCE        11

### CODE REVIEW

**Comment by mtijanic** [comment]
Step 1: Need to have the Events plugin send the data back. Add these two to `Events::SignalEvent`, after the loop:
```C
    GetServices()->m_messaging->BroadcastMessage("NWNX_EVENT_SIGNAL_EVENT_RESULT",  { eventName, *result});
    GetServices()->m_messaging->BroadcastMessage("NWNX_EVENT_SIGNAL_EVENT_SKIPPED", { eventName, std::to_string(skipped?1:0)});
```

Step 2: CombatModes must subscribe to these messages.
2a) Add `bool m_skipped;` to CombatModes.h
2b) Add this to the plugin constructor:
```C
    GetServices()->m_messaging->SubscribeMessage("NWNX_EVENT_SIGNAL_EVENT_SKIPPED",
        [this](const std::vector<std::string> message)
        {
            if (message[0] == "NWNX_ON_MODE_ON" || message[0] == "NWNX_ON_MODE_OFF")
                this->m_skipped = std::strtoul(message[1].c_str()) == 1;
        });
```

Step 3: Check `m_skipped` in `SetCombatMode` to decide whether to call the original or not.

I haven't actually compiled this code, so there might be some quirks to iron out, but it should be right in a nutshell. Ping on discord if there are issues.

**Comment by Daztek** [comment]
Added skipping functionality with thanks to Sherincall

**Comment by Liareth** [comment]
So I think I misunderstood something ... when we were discussing moving the events to a new plugin, I thought the plugin would *do* something. In other words, I thought you wanted to do something with SetCombatMode and since it was already used elsewhere, you were going to extract it, plus your functionality, to a second plugin. I'm hesitant to have a plugin here that does nothing but send messages to Events - in that case, why not just put it in Events? What are your thoughts?

**Comment by mtijanic** [comment]
Yeah, the stuff from the Weapon plugin should go here.

**Comment by Liareth** [comment]
Is this waiting for more work to add the stuff from the Weapon plugin before merging? Or is the idea to merge it now and move the stuff later?

**Comment by mtijanic** [comment]
I think it's okay to merge now. Weapon and CombatModes will be incompatible, but since this is a new plugin, that's not a big deal. And once it's in, we'll have an easier time moving the Weapon stuff in here.

**Pull request merged**
