### PR TITLE
Events: Client disconnect: Add PLAYER_NAME as event data

### PR DESCRIPTION
**Pull request by hendrikgit**

### CODE REVIEW

**Comment by Daztek** [comment]
Would you like to be fancy and add the public cdkey too?

`auto cdkey = pPlayerInfo->m_lstKeys[0].sPublic;`

**Comment by hendrikgit** [comment]
I'm happy to do that if you think it would help. It's not necessary for my usecase. I do this because I'm starting to log this information to sqlite and if I have the player name I can find the corresponding client connect event which already has all the info like cdkey.

**Comment by hendrikgit** [comment]
Done. Now there is player name and cdkey.

**Comment by Daztek** [comment]
:tada:

**Pull request merged**
