### PR TITLE
PostgreSQL enhancement.

### PR DESCRIPTION
**Pull request by ELadner**
Enhanced support for issue #2

### CODE REVIEW

**Comment by ELadner** [comment]
Oops.. that was a faux pas on my part.  I didn't mean to push the documentation into this PR.  Can you cherry pick the PostgreSQL change?

**Comment by Liareth** [comment]
I can merge it manually by cherry-picking but that doesn't generate the completed PR history on GitHub. Is there another way to do it on my end? Else I'd recommend just resetting the two commits after the one you wanted in the PR, then force pushing that to your branch.

`git reset --hard HEAD~2` will probably do it, and `git status` should see that all of your documentation changes are unstaged. Then `git push --force origin master` (replacing origin and master where appropriate) will force push to your branch and remove the accidental commits.

**Comment by ELadner** [comment]
I don't think I can undo that "merge branch" commit.  It was a result of merging down from the fork.  HEAD~1 will cut off the last commit (the documentation)?

**Comment by ELadner** [comment]
And yes.. I should be using branches. Only a yellow belt in git.

**Comment by Liareth** [comment]
That works. Or, if git is being a pain, you can just do it the ghetto way - copy all your files, delete your fork and remake it, paste all your files on top of it, then push your SQL stuff only to master, then make a new branch for documentation and a new branch for everything else from now on.

**Comment by ELadner** [comment]
how 'bout now...

**Comment by Liareth** [comment]
Looks good to me!

**Pull request merged**
