### PR TITLE
Added additional *RemainingSpellSlots() functions + bugfixes in NWNX_Creature

### PR DESCRIPTION
**Pull request by Cjreek**
- ~~GetSpellsPerDayLeft()~~
- ~~IncrementSpellsPerDayLeft()~~ >> IncrementRemainingSpellSlots()
- ~~DecrementSpellsPerDayLeft()~~ >> DecrementRemainingSpellSlots()
- ~~ResetSpellsPerDayLeft()~~ >> ResetRemainingSpellSlots()

The counter parts to the memorized spell functions for caster classes that don't memorize spells.

### CODE REVIEW

**Comment by Cjreek** [comment]
Nevermind. All of those already exist (Set instead of increment/decrement, but whatever). Please close and decline

**Comment by Cjreek** [comment]
Wait, I'll remove the duplicates and keep the increment/decrement functions and make the old ones future proof for .35

**Comment by Daztek** [comment]
Can you redo your PR without all the fixes? Basically just your additional functions, I'd like to num multiclass stuff all in one go on the .35 branch. 

And I believe `NWNX_Creature_ReadySpells` already behaves like your `NWNX_Creature_ResetRemainingSpellSlots`

**Comment by Cjreek** [comment]
Made a fresh one without any extra stuff. Closing this one

**Pull request closed without merging**
