### PR TITLE
add cp1251 locale, rework the definitions a bit

### LINKED ISSUE #985: Add support for Central European Locale (Polish)
I have noticed some issues with string encoding when using language-specific diacritic characters:
```
Message = "ę ą ś ć ź ń ó";

ISO-8859-1
[NWNX_DotNET] [DotNETExports.cpp:131] Pushing string 'e a s c z n ó'.
[NWNXLib] [Encoding.cpp:152] FromUTF: "e a s c z n ó" -> "e a s c z n �"

ISO-8859-2
[NWNX_DotNET] [DotNETExports.cpp:131] Pushing string 'ę ą ś ć ź ń ó'.
[NWNXLib] [Encoding.cpp:152] FromUTF: "ę ą ś ć ź ń ó" -> "? ? ? ? ? ? �"

UTF-8
[NWNX_DotNET] [DotNETExports.cpp:131] Pushing string 'ę ą ś ć ź ń ó'.
[NWNXLib] [Encoding.cpp:152] FromUTF: "ę ą ś ć ź ń ó" -> "? ? ? ? ? ? �"
```

Could you please add support for Central European Locale (Polish language)?

### PR DESCRIPTION
**Pull request by mtijanic**
Resolves #985 

@Mefi100 could you give this a shot?

### CODE REVIEW

**Comment by Mefi100** [comment]
Still have some issues with _FromUTF_

`D [15:55:00] [NWNXLib] [Encoding.cpp:207] FromUTF: "Posługując się tą bronią otrzymujesz karę do ataku -4." -> "Pos�?uguj�?c si�? t�? broni�? otrzymujesz kar�? do ataku -4."`

I have merged your changes into my fork https://github.com/Mefi100/unified/commit/0a949d40f16daea2dff0afea1e037449a8e739b0 , built and set environment variable 
`export NWNX_CORE_LOCALE=cp1250`

**Comment by Mefi100** [comment]
**Update:**

It works _almost_ fine! I did some tests in the game. It seems that it adds an additional, unrecognized char after PL specific characters, resulting in "ś?ż?ć?" instead of "śżć". 

Test string:
`ęąśćżźńó`

test

**Comment by plenarius** [comment]
Looks like you just need to skip the `?` if the char was found.

```c
                    case cp1250:
                    {
                        bool bFound = false;
                        for (int i = 0; i < 0x80; i++)
                        {
                            if (map_cp1250[i] == codepoint)
                            {
                                iso8859.push_back(static_cast<char>(i | 0x80));
                                bFound = true;
                                break;
                            }
                        }
                        if (!bFound)
                            iso8859.push_back('?');
                        break;
                    }
```

**Comment by mtijanic** [comment]
Ugh, yes. I think I thought `break;` would break out of the case, not the loop. I'll fix it.

**Comment by mtijanic** [comment]
Done - do you want to try it again or do we just merge and fix other stuff in a follow on?

**Comment by Mefi100** [comment]
It works! BIG thanks for this feature. It's good to merge now.

**Pull request merged**
